name = "hex-sparse-poly"
defaultTargets = ["HexSparsePoly"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "0ec35366ca67d3f4d1189cc4c9714805c5c437ec"

[[require]]
name = "HexPoly"
git = "https://github.com/leanprover/hex-poly.git"
rev = "bf67a5243d68c909bcd059a89fd9d3f1c54ba7d8"

[[lean_lib]]
name = "HexSparsePoly"
globs = [
  "HexSparsePoly",
  "HexSparsePoly.Basic",
  "HexSparsePoly.Arith",
  "HexSparsePoly.Dense",
  "HexSparsePoly.Eval",
  "HexSparsePoly.Euclid",
]

[[lean_lib]]
name = "HexSparsePolyTests"
globs = ["HexSparsePoly.KernelTests"]
