name = "hex-sparse-poly"
defaultTargets = ["HexSparsePoly"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "2d7f55d190cc2df9c9bf55437f344e65fbddc7c0"

[[require]]
name = "HexPoly"
git = "https://github.com/leanprover/hex-poly.git"
rev = "1912974c25db065544162bc455dde43b23216a82"

[[lean_lib]]
name = "HexSparsePoly"
globs = [
  "HexSparsePoly",
  "HexSparsePoly.Basic",
  "HexSparsePoly.Arith",
  "HexSparsePoly.Dense",
  "HexSparsePoly.Eval",
  "HexSparsePoly.Euclid",
]

[[lean_lib]]
name = "HexSparsePolyTests"
globs = ["HexSparsePoly.KernelTests"]
