name = "hex-sparse-poly"
defaultTargets = ["HexSparsePoly"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "591c146eeee0ef301a110cd33c19cc0cf1e07352"

[[require]]
name = "HexPoly"
git = "https://github.com/leanprover/hex-poly.git"
rev = "1ca97f372946ecc430fe4f3961ec4220f9bc7706"

[[lean_lib]]
name = "HexSparsePoly"
globs = [
  "HexSparsePoly",
  "HexSparsePoly.Basic",
  "HexSparsePoly.Arith",
  "HexSparsePoly.Dense",
  "HexSparsePoly.Eval",
  "HexSparsePoly.Euclid",
]

[[lean_lib]]
name = "HexSparsePolyTests"
globs = ["HexSparsePoly.KernelTests"]
