name = "hex-sparse-poly-conformance"
defaultTargets = ["HexSparsePolyConformance"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexSparsePoly"
path = ".."

[[require]]
name = "hex-test-kit"
git = "https://github.com/leanprover/hex-test-kit.git"
rev = "26e3c46c6263b741a6e1fdaf5e5fc03832ec5b79"

[[require]]
name = "HexModArith"
git = "https://github.com/leanprover/hex-mod-arith.git"
rev = "fef691d088652cb43c995634be2c420291080407"

[[lean_lib]]
name = "HexSparsePolyConformance"
globs = [
  "HexSparsePolyFixtures",
  "HexSparsePoly.Conformance",
]

[[lean_exe]]
name = "hexsparsepoly_emit_fixtures"
root = "HexSparsePoly.EmitFixtures"
