name = "hex-sparse-poly-bench"
defaultTargets = ["hexsparsepoly_bench"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexSparsePoly"
path = ".."

[[require]]
name = "HexModArith"
git = "https://github.com/leanprover/hex-mod-arith.git"
rev = "2df407d09c7362ad9e755b293034517a0b3c7ef5"

[[require]]
name = "HexPolyFp"
git = "https://github.com/leanprover/hex-poly-fp.git"
rev = "1a21ec21624b3353559d0d6f386e5d5f24ccbc62"

[[require]]
name = "lean-bench"
git = "https://github.com/kim-em/lean-bench.git"
rev = "master"

[[lean_exe]]
name = "hexsparsepoly_bench"
root = "HexSparsePoly.Bench"
